using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Diagnostics;
using System.Net.Sockets;
using System.Threading;
using System.Windows.Forms;
using IPAddressControlLib;

namespace AutoLead
{
    public partial class Form1
    {
        private System.Windows.Forms.Timer settingtime = new System.Windows.Forms.Timer();
        public int changes = 0;
        public int c_listoff = 0;
        public int c_ssh = 0;
        public int c_vip = 0;
        public int c_lumi = 0;
        public int c_othersetting = 0;
        public int c_startall = 0;
        public int c_resetall = 0;
        public int c_stopall = 0;
        public int changeslocal = 0;
        private bool isconnected = false;
        public int changesssh = 0;
        public int c_listofflocal = 0;
        public int c_sshlocal = 0;
        public int c_viplocal = 0;
        public int c_lumilocal = 0;
        public int c_othersettinglocal = 0;
        public int c_startalllocal = 0;
        public int c_resetalllocal = 0;
        public int c_stopalllocal = 0;
        public string scriptstatus = "stop";
        public string clientver = "6.5";
        public string curip = "";
        private Thread IPThread;
        public List<geo> listGeo = new List<geo>();
        private bool _sshssh = false;
        private string privatekey = "autoleadios";

        public string documentfolder =
            string.Concat(Environment.GetFolderPath(Environment.SpecialFolder.Personal), "\\");

        private string serverurl = "http://nam72.lake.gq/random1/deviceinfo/";
        private string sshserverurl = "http://none.com";
        private Socket _clientSocket;
        private List<string> _listcountry = new List<string>();
        private List<offerItem> offerListItem = new List<offerItem>();
        private command cmd = new command();
        private byte[] _buffer;
        private string dataleft;
        private deviceInfo DeviceInfo = new deviceInfo();
        private List<appDetail> AppList = new List<appDetail>();
        private List<appDetail> AppList1 = new List<appDetail>();
        private OfferOption optionform = new OfferOption();
        private DownloadProgress downloadform = new DownloadProgress();
        public commandResult cmdResult = new commandResult();
        private int maxwait = 120;
        private int maxwait1 = 60;
        private List<Carrier> carrierList = new List<Carrier>();
        private List<countrycodeiOS> listcountrycodeiOS = new List<countrycodeiOS>();
        private List<languagecode> listlanguagecode = new List<languagecode>();
        private List<ssh> listssh = new List<ssh>();
        private List<backup> listbackup = new List<backup>();
        private string oriadd = "";
        private int oriport = 0;
        private List<string> listcommand = new List<string>();

        private List<vipaccount> listvipacc = new List<vipaccount>();
        private List<luminatio_account> listlumiacc = new List<luminatio_account>();

        private List<countrycode> listcountrycode = new List<countrycode>();
        private List<AutoLead.Script> listscript = new List<AutoLead.Script>();
        private Process bitproc = new Process();
        private Thread oThread;
        private string usCulture = "en-US";
        private IFormatProvider usformat;
        private int runningstt = 0;
        private ListViewColumnSorter lvwColumnSorter;
        private Thread bkThread;
        private int iOSversion;
        private int recordstep = 0;
        private int prevx = 0;
        private int first = 0;
        private int runtime = 0;
        private int backuptime = 0;
        private int prevy = 0;
        private ssh _getssh;



        private vipaccount vipacc;
        private string currentvipip;

        private luminatio_account lumiacc;
        private string currentlumiip;

        private List<string> listfirstname = new List<string>();
        private List<string> listlastname = new List<string>();
        private List<string> listemaildomain = new List<string>();
        private List<string> listtimezone = new List<string>();
        private DateTime clicklast;
        private DateTime recprev;
        private ReadOnlyCollection<TimeZoneInfo> tz = TimeZoneInfo.GetSystemTimeZones();
        private readonly static Random getrandom;
        private readonly static object syncLock;
        private List<NumericUpDown> listRRSmin = new List<NumericUpDown>();
        private List<NumericUpDown> listRRSmax = new List<NumericUpDown>();
        private IContainer components = null;
        private Button button1;
        private Label label1;
        private Label label2;
        private Button button2;
        private IPAddressControl DeviceIpControl;
        private Label label3;
        private Label label4;
        private ComboBox proxytool;
        private Label label5;
        private Label labelSerial;
        private NumericUpDown numericUpDown1;
        private Label label6;
        private Label label20;
        private ComboBox comboBox5;
        private Label label21;
        private IPAddressControl ipAddressControl1;
        private Button button23;
        private GroupBox groupBox1;
        private Button button20;
        private Label label12;
        private CheckBox autoreconnect;
        private System.Windows.Forms.ContextMenuStrip contextMenuStrip1;
        private ToolStripMenuItem deleteToolStripMenuItem;
        private System.Windows.Forms.ContextMenuStrip contextMenuStrip2;
        private ToolStripMenuItem deleteToolStripMenuItem1;
        private ToolStripMenuItem moveToSlotToolStripMenuItem;
        private ToolStripMenuItem toolStripMenuItem1;
        private ImageList imageList1;
        private System.Windows.Forms.ContextMenuStrip contextMenuStrip3;
        private ToolStripMenuItem bảoVệDữLiệuToolStripMenuItem;
        private System.Windows.Forms.ContextMenuStrip contextMenuStrip4;
        private ToolStripMenuItem deleteToolStripMenuItem2;
        private TabPage tabPage5;
        private Label label25;
        private Label label24;
        private Label label23;
        private Label label13;
        private PictureBox pictureBox5;
        private PictureBox pictureBox4;
        private PictureBox pictureBox3;
        private PictureBox pictureBox2;
        private TabPage tabPage10;
        private Button button54;
        private CheckBox checkBox16;
        private Button button53;
        private Button button52;
        private Button button51;
        private Button button50;
        private Button button49;
        private Button button48;
        private Button button47;
        private Button button46;
        private Button button45;
        private Button button44;
        private Button button43;
        private Button button42;
        private Button button41;
        private Button button40;
        private Button button39;
        private Button button38;
        private Button button37;
        private TabPage tabPage9;
        private GroupBox groupBox8;
        private Label napcodestt;
        private TextBox deviceseri;
        private Button button36;
        private Label label36;
        private TextBox code;
        private Label label37;
        private TabPage Script;
        private TextBox textBox9;
        private Label label33;
        private Button button34;
        private Button button33;
        private Button button32;
        private ListView listView7;
        private ColumnHeader columnHeader14;
        private TextBox textBox6;
        private ListView listView6;
        private ColumnHeader columnHeader13;
        private TabPage tabPage6;
        private TextBox textBox5;
        private ListView listView5;
        private GroupBox groupBox6;
        private CheckBox checkBox20;
        private NumericUpDown longtitude;
        private Label ltimezone;
        private CheckBox checkBox19;
        private CheckBox checkBox13;
        private Label label41;
        private CheckBox checkBox5;
        private Label label40;
        private CheckBox checkBox9;
        private NumericUpDown latitude;
        private ComboBox carrierBox;
        private CheckBox fakelang;
        private ComboBox comboBox2;
        private ComboBox comboBox1;
        private GroupBox groupBox7;
        private Label label63;
        private Label label43;
        private NumericUpDown numericUpDown10;
        private Label label31;
        private Label label32;
        private NumericUpDown numericUpDown5;
        private CheckBox checkBox4;
        private NumericUpDown numericUpDown4;
        private Label label30;
        private GroupBox groupBox9;
        private CheckBox fakeversion;
        private CheckBox iphone;
        private CheckBox ipad;
        private CheckBox ipod;
        private CheckBox checkBox11;
        private CheckBox fakemodel;
        private Label fileofname;
        private CheckBox fakedevice;
        private CheckBox checkBox15;
        private CheckBox checkBox14;
        private TabPage tabPage8;
        private RichTextBox textBox2;
        private Button button64;
        private Button button35;
        private Button button30;
        private TrackBar trackBar1;
        private GroupBox groupBox4;
        private Button button11;
        private TextBox textBox1;
        private GroupBox groupBox3;
        private Button button26;
        private TextBox textBox7;
        private Label label18;
        private Label label19;
        private TextBox textBox8;
        private TextBox textBox3;
        private Button button18;
        private GroupBox groupBox5;
        private Button button28;
        private Label label11;
        private Button button13;
        private Button button12;

        private Button button10;
        

        private ComboBox wipecombo;
        private PictureBox pictureBox1;
        private TabPage tabPage7;
        private Label label35;
        private Label label34;
        private CheckBox checkBox7;
        private ComboBox comboBox3;
        private CheckBox checkBox6;
        private Button button31;
        private Label label26;
        private TextBox textBox4;
        private Button button29;
        private Button button27;
        private Label label9;
        private NumericUpDown rsswaitnum;
        private Label label8;
        private Button bkreset;
        private Button button19;
        private Button button17;
        private Button button16;
        private Button button15;
        private ListView listView4;
        private ColumnHeader columnHeader10;
        private ColumnHeader columnHeader7;
        private ColumnHeader columnHeader11;
        private ColumnHeader columnHeader12;
        private ColumnHeader columnHeader8;
        private ColumnHeader columnHeader9;
        private ColumnHeader columnHeader15;
        private ColumnHeader columnHeader16;
        private TabPage tabPage2;
        private TabControl tabControl2;
        private TabPage tabPage3;
        private CheckBox checkBox17;
        private Label ss_dead;
        private Label ssh_used;
        private Label ssh_live;
        private Label ssh_uncheck;
        private NumericUpDown numericUpDown2;
        private Label label14;
        private Label labeltotalssh;
        private Button button25;
        private Button button24;
        private Button button22;
        private Button button8;
        private Button button14;
        private Button button9;
        private Button importfromfile;
        private ListView listView2;
        private ColumnHeader columnHeader1;
        private ColumnHeader columnHeader2;
        private ColumnHeader columnHeader3;
        private ColumnHeader columnHeader4;


        private TabPage tabPageQuan4;
        private GroupBox groupBoxQuan2;
        private TextBox lumipassword;
        private TextBox lumiid;
        private TextBox lumizone;
        private Label labelQuan10;
        private Label labelQuan7;
        private Label labelQuanZone;
        private Button lumiadd;
        private Button lumidelete;
        private ListView listViewQuan3;
        private ColumnHeader columnHeaderQuan5;
        private ColumnHeader columnHeaderQuan6;
        private ColumnHeader columnHeaderQuanZone;

        private TabPage tabPage4;
        private CheckBox sameVip;
        private Button button57;
        private GroupBox groupBox2;
        private TextBox vippassword;
        private TextBox vipid;
        private Label label10;
        private Label label7;
        private Button vipadd;
        private Button vipdelete;
        private ListView listView3;
        private ColumnHeader columnHeader5;
        private ColumnHeader columnHeader6;

        private TabPage tabPage1;
        private TextBox textBox11;
        private TextBox comment;
        private Label label44;
        private CheckBox checkBox18;
        private CheckBox checkBox12;
        private NumericUpDown numericUpDown6;
        private CheckBox checkBox10;
        private Label backuprate;
        private Label backupoftime;
        private Label runoftime;
        private Label label29;
        private Label label28;
        private NumericUpDown numericUpDown3;
        private Label label27;
        private NumericUpDown itunesY;
        private Label label22;
        private NumericUpDown itunesX;
        private Label label17;
        private NumericUpDown safariY;
        private Label label16;
        private NumericUpDown safariX;
        private Label label15;
        private Button button21;
        private Button Reset;
        private CheckBox checkBox3;
        private CheckBox checkBox2;
        private Button button7;
        private CheckBox checkBox1;
        private Button button6;
        private Button button5;
        private Button button4;
        private Button button3;
        private ListView listView1;
        private ColumnHeader offername;
        private ColumnHeader offerurl;
        private ColumnHeader appname;
        private ColumnHeader timedelay;
        private ColumnHeader usescript;
        private TabControl Contact;
        private CheckBox fakeregion;
        private Button pausescript;
        private Label l_autover;
        public string proxytype { get; private set; }
        public bool svip { get; private set; }
    }
}